### PR TITLE
Feature/enable about section

### PR DESCRIPTION
**Pull request by vicmaster**
* Enable about partial
* Add wdt promo youtube video
* Optimize background image for web

### CODE REVIEW

**Comment by vicmaster** [comment]
@joiggama check this out please!

**Comment by TheNaoX** [comment]
This one looks okay I think :P

**Comment by vicmaster** [comment]
Hahaha I was expecting a LGTM :p

**Comment by TheNaoX** [comment]
That's another way to say it jaja, :shipit:

**Pull request merged**
